### ISSUE TITLE
crash on open with `panic: runtime error: slice bounds out of range`

### ISSUE THREAD

**Issue by ervinpopescu** [gokcehan/lf#1613]
**Log (lf-git on Arch):**
```console
$ lf
panic: runtime error: slice bounds out of range [:-1]

goroutine 1 [running]:
main.(*nav).readTags(0xc000083500)
    github.com/gokcehan/lf/nav.go:1928 +0x3df
main.(*nav).sync(0xc000083500)
    github.com/gokcehan/lf/nav.go:1611 +0x225
main.run()
    github.com/gokcehan/lf/client.go:58 +0x289
main.main()
    github.com/gokcehan/lf/main.go:357 +0x819
```

**Version:**
```console
$ lf --version
31.r49.g0c02239
```

**Failing function**:
```go
func (nav *nav) readTags() error {
	nav.tags = make(map[string]string)
	f, err := os.Open(gTagsPath)
	if os.IsNotExist(err) {
		return nil
	}
	if err != nil {
		return fmt.Errorf("opening tags file: %s", err)
	}
	defer f.Close()

	scanner := bufio.NewScanner(f)
	for scanner.Scan() {
		text := scanner.Text()
		ind := strings.LastIndex(text, ":")
		path := text[0:ind]
		mark := text[ind+1:]
		if _, ok := nav.tags[path]; !ok {
			nav.tags[path] = mark
		}
	}

	if err := scanner.Err(); err != nil {
		return fmt.Errorf("reading tags file: %s", err)
	}

	return nil
}
```

**Failing indexing:**
```go
		path := text[0:ind]
```

**Comment by ervinpopescu** [comment]
Figured it out. I removed the entire `$XDG_DATA_HOME/share/lf` directory while doing my regular cleaning and apparently when you do that, `lf` recreates it with the following tree:
```console
$ tree $XDG_DATA_HOME/lf
/home/user/.local/share/lf
├── files
├── history
└── tags
```

```console
$ ls -l ~/.local/share/lf/tags                                                                                                         
-rw-r--r-- 1 ervin ervin 0 Feb 24 19:20 /home/ervin/.local/share/lf/tags
```

From the function, I can tell that `lf` expects to find something in there and when it doesn't, the panic occurs.
