### ISSUE TITLE
After updating lf amd64 version from r15 to r16 or r17 on FreeBSD, it stopped working.

### ISSUE THREAD

**Issue by tukiyo** [gokcehan/lf#516]
FreeBSD 9.1-RELEASE-p24

```sh
$ ./lf -version
r16
$ ./lf -h
Usage of ./lf:
  -command string
        command to execute on client initialization
  -cpuprofile string
        path to the file to write the CPU profile
  -doc
        show documentation
  -last-dir-path string
        path to the file to write the last dir on exit (to use for cd)
  -memprofile string
        path to the file to write the memory profile
  -remote string
        send remote command to server
  -selection-path string
        path to the file to write selected files on open (to use as open file dialog)
  -server
        start server (automatic)
  -version
        show version
$ ./lf
runtime: pipe failed with -78
fatal error: runtime: pipe failed

goroutine 1 [running]:
runtime.throw(0x5ef162, 0x14)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/panic.go:1116 +0x72 fp=0xc00003d848 sp=0xc00003d818 pc=0x434ed2
runtime.netpollinit()
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/netpoll_kqueue.go:34 +0x19e fp=0xc00003d8d0 sp=0xc00003d848 pc=0x43113e
runtime.netpollGenericInit()
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/netpoll.go:122 +0x67 fp=0xc00003d8e8 sp=0xc00003d8d0 pc=0x430727
internal/poll.runtime_pollServerInit()
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/netpoll.go:114 +0x25 fp=0xc00003d8f8 sp=0xc00003d8e8 pc=0x4640a5
sync.(*Once).doSlow(0x751828, 0x5fe600)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/sync/once.go:66 +0xec fp=0xc00003d948 sp=0xc00003d8f8 pc=0x47266c
sync.(*Once).Do(...)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/sync/once.go:57
internal/poll.(*pollDesc).init(0xc00004c558, 0xc00004c540, 0x0, 0x0)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/internal/poll/fd_poll_runtime.go:38 +0x133 fp=0xc00003d980 sp=0xc00003d948 pc=0x4bbfb3
internal/poll.(*FD).Init(0xc00004c540, 0x5eab24, 0x4, 0x1, 0x1f, 0xc00003da28)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/internal/poll/fd_unix.go:62 +0x5f fp=0xc00003d9b0 sp=0xc00003d980 pc=0x4bc91f
os.newFile(0x3, 0x5ebce2, 0x9, 0x1, 0x3)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/os/file_unix.go:155 +0x131 fp=0xc00003dae0 sp=0xc00003d9b0 pc=0x4c3131
os.openFileNolog(0x5ebce2, 0x9, 0x0, 0xc000000000, 0x0, 0x18, 0x18)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/os/file_unix.go:224 +0x1ce fp=0xc00003db48 sp=0xc00003dae0 pc=0x4c34ae
os.OpenFile(0x5ebce2, 0x9, 0x0, 0x0, 0x74b678, 0x203000, 0x203000)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/os/file.go:327 +0x65 fp=0xc00003db90 sp=0xc00003db48 pc=0x4c2345
os.Open(...)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/os/file.go:307
os/exec.(*Cmd).stdin(0xc000170000, 0x0, 0x3, 0xc00000c920)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/os/exec/exec.go:246 +0x3ea fp=0xc00003dc10 sp=0xc00003db90 pc=0x4db42a
os/exec.(*Cmd).Start(0xc000170000, 0x4, 0xc00003dd88)
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/os/exec/exec.go:407 +0x162 fp=0xc00003dd48 sp=0xc00003dc10 pc=0x4dbf02
main.startServer()
        /home/travis/gopath/src/github.com/gokcehan/lf/main.go:67 +0xb4 fp=0xc00003dda8 sp=0xc00003dd48 pc=0x576cd4
main.checkServer()
        /home/travis/gopath/src/github.com/gokcehan/lf/main.go:75 +0xd6 fp=0xc00003ddf8 sp=0xc00003dda8 pc=0x576e36
main.main()
        /home/travis/gopath/src/github.com/gokcehan/lf/main.go:162 +0x7bb fp=0xc00003df88 sp=0xc00003ddf8 pc=0x57767b
runtime.main()
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/proc.go:204 +0x209 fp=0xc00003dfe0 sp=0xc00003df88 pc=0x4376c9
runtime.goexit()
        /home/travis/.gimme/versions/go1.15.linux.amd64/src/runtime/asm_amd64.s:1374 +0x1 fp=0xc00003dfe8 sp=0xc00003dfe0 pc=0x4696e1
$
```

**Comment by gokcehan** [comment]
@tukiyo r16 is the version we switched from termbox to tcell which is probably be related this. It's a shame because we had some issues reported in OpenBSD before and I was hoping tcell might work better. Unfortunately I don't have much motivation to work on bugs in other platforms than the ones I'm using so we need FreeBSD contributors to look into this issue in either lf or tcell side. I'm pinning the issue and marking it with help tag to catch some attention.

**Comment by Limero** [comment]
On GhostBSD (desktop based on FreeBSD 12.2) both the r19 lf-freebsd-amd64 version from Github releases and the master branch built from scratch works for me.

I see that you are using FreeBSD 9.1 which [has reached End-Of-Life](https://www.freebsd.org/releases/), so that might be the problem.

**Comment by tukiyo** [comment]
@Limero 
Oh.. EOL, thank you.
