### ISSUE TITLE
error running on mipsle device

### ISSUE THREAD

**Issue by bartsimp** [gokcehan/lf#519]
Hello 

trying to execute the mipsle version r17 (lf-linux-mipsle.tar.gz) on a busybox based device,
I got the following error:
```
/tmp/hdd/volumes/HDD1/Linux/lf-linux-mipsle # ./lf
futexwakeup addr=0x39b1d4 returned -89
fatal error: unexpected signal during runtime execution
[signal SIGSEGV: segmentation violation code=0x80 addr=0x0 pc=0x48fb4]

runtime stack:
runtime.throw(0x26fea1, 0x2a)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/panic.go:1116 +0x60
runtime.sigpanic()
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/signal_unix.go:704 +0x554
runtime.futexwakeup(0x39b1d4, 0x1)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/os_linux.go:70 +0x90
runtime.notewakeup(0x39b1d4)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/lock_futex.go:144 +0x68
runtime.startlockedm(0x4000e0)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/proc.go:2100 +0x8c
runtime.schedule()
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/proc.go:2704 +0x74
runtime.park_m(0x400540)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/proc.go:2837 +0xa4
runtime.mcall(0x0)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_mipsx.s:151 +0x54

goroutine 1 [chan receive, locked to thread]:
runtime.gopark(0x27e520, 0x434030, 0x170e, 0x2)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/proc.go:306 +0xf8
runtime.chanrecv(0x434000, 0x0, 0x400001, 0x20101)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/chan.go:567 +0x3a0
runtime.chanrecv1(0x434000, 0x0)
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/chan.go:434 +0x28
runtime.gcenable()
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/mgc.go:220 +0xb8
runtime.main()
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/proc.go:167 +0x13c
runtime.goexit()
        /home/travis/.gimme/versions/go1.15.2.linux.amd64/src/runtime/asm_mipsx.s:651 +0x4
/tmp/hdd/volumes/HDD1/Linux/lf-linux-mipsle #

```

can you help me?

**Comment by gokcehan** [comment]
@bartsimp Sorry I don't have a mipsle machine so I don't think I can help. Also I don't know what you mean by a busybox based device.

**Comment by bartsimp** [comment]
Thanks for answer @gokcehan. With "busybox based device" I mean a mediaplayer based on Realtek RTD1261 chipset whose firmware is a linux based operating system: BusyBox 1.1.3

**Comment by gokcehan** [comment]
@bartsimp I'm confused with the terminology used here. I don't understand why you are calling linux a firmware and busybox an OS. What does `uname -sm` show?

**Comment by bartsimp** [comment]
```
Venus login: root

BusyBox v1.1.3 (2008.03.17-07:41+0000) Built-in shell (ash)
Enter 'help' for a list of built-in commands.

/ # uname -sm
Linux mips
/ # uname -a
Linux Venus 2.6.12.6-VENUS #8 Thu Mar 27 11:58:33 CST 2008 mips unknown

```

**Comment by gokcehan** [comment]
@bartsimp It's no problem I'm just trying to make sure. As you are probably aware, I'm not able to test this on each platform in the list other than the ones I use myself. I simply upload those binaries if they are able to compile without an error and rely on user reports to see whether it works or not. It seems that it does not work in your machine for some reason. Your stacktrace in your post does not show anything in our code base and tcell. So the issue is probably somehow related to Go language itself. Maybe something about channels/goroutines are not supported on your machine. Unfortunately, I don't think there is much we can do to fix this on our side.

**Comment by bartsimp** [comment]
thanks anyway for your time @gokcehan
