### ISSUE TITLE
lf r23 crashes by deleting a file with long name

### ISSUE THREAD

**Issue by ynakao** [gokcehan/lf#648]
I'm using Arch Linux and installed lf from [lf-bin](https://aur.archlinux.org/packages/lf-bin/) in AUR.

### Issue

After upgraded to r23, when I try to delete files with long names, lf crashes saying the following message in broken format.

```shell
panic: runtime error: slice bounds out of range [1:0]

                                              goroutine 1 [running]:
                                                                    main.(*ui).draw(0xc0000d6000, 0xc0000c4160)
                                                                                                                /home/travis/gopath/src/github.com/gokcehan/lf/ui.go:849 +0x11c5
                                                         main.(*app).loop(0xc00009c080)
                                                                                        /home/travis/gopath/src/github.com/gokcehan/lf/app.go:430 +0x9cf
                                 main.run()
                                                /home/travis/gopath/src/github.com/gokcehan/lf/client.go:53 +0x35c
                                                                                                                  main.main()
        /home/travis/gopath/src/github.com/gokcehan/lf/main.go:296 +0x74a
```

For easy to read, this is the formatted version removing leading spaces.

```shell
panic: runtime error: slice bounds out of range [1:0]

goroutine 1 [running]:
main.(*ui).draw(0xc0000d6000, 0xc0000c4160)
/home/travis/gopath/src/github.com/gokcehan/lf/ui.go:849 +0x11c5
main.(*app).loop(0xc00009c080)
/home/travis/gopath/src/github.com/gokcehan/lf/app.go:430 +0x9cf
main.run()
/home/travis/gopath/src/github.com/gokcehan/lf/client.go:53 +0x35c
main.main()
/home/travis/gopath/src/github.com/gokcehan/lf/main.go:296 +0x74a
```

After that, other outputs are also displayed in broken format.

```shell
$ lf -help
Usage of lf:
              -command value
                                        command to execute on client initialization
                                                                                     -config string
                                                                                                        path to the config file (instead of the usual paths)
                                       -cpuprofile string
                                                                path to the file to write the CPU profile
                                                                                                           -doc
                                                                                                                      show documentation
                   -last-dir-path string
                                                path to the file to write the last dir on exit (to use for cd)
                                                                                                                -memprofile string
                path to the file to write the memory profile
                                                              -remote string
                                                                                        send remote command to server
                                                                                                                       -selection-path string
                                path to the file to write selected files on open (to use as open file dialog)
                                                                                                               -server
                                                                                                                               start server (automatic)
                                  -single
                                                start a client without server
                                                                               -version
                                                                                                show version
```

### Step to reproduce

1. Delete all /tmp/lf.${USER}.* files

```shell
$ rm /tmp/lf.ynakao.*
```

2. Create a file with long name.

```shell
$ touch aaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaaa.txt
```

3. Launch lf with empty config and execute the command `:delete` on that file.

```shell
$ touch empty_lfrc
$ lf -config empty-lfrc
```

- Output of log files

/tmp/lf.ynakao.136358.log 
```
2021/06/12 11:55:43 hi!
2021/06/12 11:55:43 loading files: []
2021/06/12 11:55:43 reading file: empty_lfrc
2021/06/12 11:55:43 loading files: []
2021/06/12 11:55:49 command: delete
```

/tmp/lf.ynakao.server.log
```
2021/06/12 11:55:43 hi!
2021/06/12 11:55:43 listen: conn 136358
```

### Other notes

- How long are file names required to crash depends on the terminal width. In my case, when terminal width is `$COLUMN=119`, file names need to be >= 88 characters. And when `$COLUMN=80`, file names need to be >= 50 characters.

- lf works fine by downgrading to version r22.

```shell
$ sudo pacman -U /var/cache/pacman/pkg/lf-bin-22-1-x86_64.pkg.tar.zst
```

**Comment by gokcehan** [comment]
@ynakao Thanks for the report. I have now pushed a fix for the issue. I'm thinking of pushing a new bug fix release soon. You can either build from the source or keep using r22 in the meantime.

By the way, you can use `reset` in the terminal to have it display the output with properly after such crashes though we should ideally have no such crashes in the program anyways.

**Comment by ynakao** [comment]
Thank you for quick fix and teaching me `reset` tip! I just compiled and installed the -git version, and file deletion works properly. So I'll close this issue.
